### ISSUE TITLE
关于渲染页面的时候传递user数据的问题

### ISSUE THREAD

**Issue by 16sixteen** [ValenW/Online-Studio#111]
`res.render('individual', {
	user: user
});`
*user表*中有*用户名*和*密码*，如果直接传整一个user表的话可能会很轻易的把*username*和*password*的数据泄露出去，因此在后台往前端传递user信息的时候，不要轻易传整个表的数据，应该选择性的传递user表中的字段，把需要保密的字段去掉（不传递）

@MchCyLh @13331151 @ValenW @linytsysu @SimbaScorpio

**Comment by linytsysu** [comment]
完全同意。谁写的，改。

**Comment by ValenW** [comment]
已修改，merge到master就可以自动关闭这个issue了。

**Comment by MchCyLh** [comment]
好的
